Real kilometros, total

Inicio

   Escriba "Ingrese la cantidad de kilometros recorridos: "
   Lea kilometros

   Si kilometros <= 300 Entonces
      total <- 100000
   Sino
      Si kilometros <= 1000 Entonces
         total <- 100000 + (kilometros * 1000)
      Sino
         total <- 100000 + (700 * 1000) + ((kilometros - 1000) * 500)
      Fin Si
   Fin Si

   Escriba "Total a pagar: ", total

Fin
