Entero numeroSerie

Inicio

   Escriba "Ingrese el numero de serie: "
   Lea numeroSerie

   Si ((numeroSerie >= 1468) Y (numeroSerie <= 1568)) 
      O ((numeroSerie >= 7000) Y (numeroSerie <= 7999)) 
      O ((numeroSerie >= 8883) Y (numeroSerie <= 9001)) Entonces

      Escriba "El producto es DEFECTUOSO"

   Sino

      Escriba "El producto NO es defectuoso"

   Fin Si

Fin
